services:
  database:
    container_name: PostgreSQL
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  backend:
    container_name: NestJS
    build: ./backend
    ports: 
      - "8000:8000"
    depends_on:
      database:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    container_name: React
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

volumes:
  database:
    driver: local
